name: Notify

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send notification using POST request
        run: |
          curl -X POST https://sctapi.ftqq.com/SCT11690TFumzw9eIs6TGTVNLiogPzpoR.send \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "title=Shiro更新完成&desp=Shiro更新完成&channel=8"

